runtime: java11
entrypoint: ls

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /js/(.*\.js)
  static_files: static/js/\1
  upload: static/js/(.*\.js)

- url: /css/(.*\.css)
  static_files: static/css/\1
  upload: static/css/(.*\.css)
