name: Build and Test Groovy Executor

on:
  pull_request:
  push:
    branches-ignore:
      - gh-pages
    paths:
      - functions/pom.xml
      - functions/groovy-executor/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ['groovy_3_0', 'groovy_2_5', 'groovy_4_0']
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven wrapper and dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: test-groovy-executor-${{ runner.os }}}-variant-${{ matrix.variant }}-mvn-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            test-groovy-executor-${{ runner.os }}}-variant-${{ matrix.variant }}-
            test-groovy-executor-${{ runner.os }}-
      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: test
        run: |
          pushd functions/groovy-executor
          ../../mvnw -B -V package -P ${{ matrix.variant }}
