name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ['groovy_3_0', 'groovy_2_5'] # disable 'groovy_4_0_alpha3' for now
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven wrapper and dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: test-${{ runner.os }}}-variant-${{ matrix.variant }}-mvn-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            test-${{ runner.os }}}-variant-${{ matrix.variant }}-
            test-${{ runner.os }}-
      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: test
        run: |
          pushd functions/function-executor
          ../../mvnw -B -V package -P ${{ matrix.variant }}
