name: Deploy Groovy Executor

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ['groovy_3_0', 'groovy_2_5', 'groovy_4_0']
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven wrapper and dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: deploy-groovy-executor-${{ runner.os }}-variant-${{ matrix.variant }}-mvn--${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            deploy-groovy-executor-${{ runner.os }}-variant-${{ matrix.variant }}-
            deploy-groovy-executor-${{ runner.os }}-
      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build jar
        run: |
          pushd functions/groovy-executor
          ../../mvnw -B -V package -P ${{ matrix.variant }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true
      - id: Deploy
        run: |
          gcloud functions deploy ${{ matrix.variant }} --entry-point gwc.GFunctionExecutor --runtime java11 --trigger-http --memory 8192MB --allow-unauthenticated --source functions/groovy-executor/target/deployment --region europe-west1 --service-account minimal-sa@gwc-experiment.iam.gserviceaccount.com

